### ISSUE TITLE
Design lo-fi mockups.

### ISSUE THREAD

**Issue by FriedDust** [shrishant/GharKoAchar#2]

**Comment by shrishant** [comment]
Dai, I have talked with the customer. The design is very very simple, he just wants the following requirement to be completed for now.
1) Have a data base to store the users
2) Do the CRUD operation on the stored users
3) Search Users with their phone number.

So, I have drawn the following lo-fi, hope it is acceptable.

![IMG20200503144325](https://user-images.githubusercontent.com/52312480/80910800-ca0df080-8d51-11ea-88e7-bc58c8a18662.jpg)

![IMG20200503144314](https://user-images.githubusercontent.com/52312480/80910798-c7130000-8d51-11ea-972b-6c4be88468f0.jpg)

I will also put the images on a folder in the project.

**Comment by shrishant** [comment]
I will finish the UI today itself, and finish the storage of data by next 2 days.

**Comment by shrishant** [comment]
Sorry for the inconvenience that I could not submit a proper lo-fi rot the project, but as per the requirement, I have designed a UI.
If any changes need to be made in the design. Please let me know
![lo-fi1](https://user-images.githubusercontent.com/52312480/80934500-3f2c0500-8de8-11ea-8df5-41950f68e303.png)
![lo-fi2](https://user-images.githubusercontent.com/52312480/80934504-40f5c880-8de8-11ea-9927-8ebd83f7e5e9.png)
