### ISSUE TITLE
Describe the data model

### ISSUE THREAD

**Issue by FriedDust** [shrishant/GharKoAchar#3]
Describe the data structure that's going to be stored into the firebase.

**Comment by shrishant** [comment]
The firebase uses the data structure similar to maps or javascript objects, which has key value pairs to store.

**Comment by FriedDust** [comment]
Yes, please describe the same object model here.

**Comment by shrishant** [comment]
Sir, for now, the object model is as follows.
Name(string)
Surname(string)
Number(Number)
Address(string)
orders(Number)
Review(string)
The data model may change on the future as per the requirement.
